# Site settings
title: "Startseite Knecht | Knecht Holding AG"
subtitle: "Knecht Holding AG"
description: "Startseite Knecht Holding AG"
baseurl: ""
url: "http://139.59.215.129"
#url: "http://127.0.0.1:4000"
author: "Knecht AG"
markdown: kramdown
## Default image size: 700x360
