source "https://rubygems.org"
gem "bundler"
gem "jekyll"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-last-modified-at"
gem 'jekyll-archives', '~> 2.1', '>= 2.1.1'
gem 'hash-joiner'
gem 'json'
